# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-TicketAuth
version:      1.01
version_from: lib/WebService/TicketAuth.pm
installdirs:  site
requires:
    Digest::MD5:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.20
